[package]
name = "extract-hist"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]
edition = "2018"

[dependencies]
hdrhistogram = "7"
trawler = "0.11.0-alpha.1"
clap = "2.31.2"
regex = "1.0"
base64 = "0.12"
